# Generated by Django 4.2.5 on 2023-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp',
            options={'verbose_name_plural': 'MPs'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
